(function(){
'use strict';
const LANGS={
 en:{name:'English',flag:'🇺🇸',country:'United States',code:'en'},
 hi:{name:'हिंदी',flag:'🇮🇳',country:'India',code:'hi'},
 es:{name:'Español',flag:'🇪🇸',country:'Spain',code:'es'},
 pt:{name:'Português',flag:'🇧🇷',country:'Brazil',code:'pt'},
 fr:{name:'Français',flag:'🇫🇷',country:'France',code:'fr'},
 de:{name:'Deutsch',flag:'🇩🇪',country:'Germany',code:'de'},
 it:{name:'Italiano',flag:'🇮🇹',country:'Italy',code:'it'},
 tr:{name:'Türkçe',flag:'🇹🇷',country:'Türkiye',code:'tr'},
 ja:{name:'日本語',flag:'🇯🇵',country:'Japan',code:'ja'},
 ko:{name:'한국어',flag:'🇰🇷',country:'South Korea',code:'ko'}
};
const INDIA_STATES=['Andhra Pradesh','Assam','Bihar','Chhattisgarh','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Odisha','Punjab','Rajasthan','Tamil Nadu','Telangana','Uttar Pradesh','Uttarakhand','West Bengal'];
const STATE_LANG={Gujarat:'hi',Maharashtra:'hi',Rajasthan:'hi',Delhi:'hi',Haryana:'hi',Punjab:'hi',Uttar_Pradesh:'hi',Madhya_Pradesh:'hi',Bihar:'hi',Jharkhand:'hi',Chhattisgarh:'hi',Uttarakhand:'hi',Himachal_Pradesh:'hi',Goa:'en',Assam:'en',West_Bengal:'en',Odisha:'en',Karnataka:'en',Kerala:'en',Tamil_Nadu:'en',Telangana:'en',Andhra_Pradesh:'en'};
const T={
 en:{navTools:'Tools',navRewards:'🎁 Rewards',navWinners:'🏆 Winners',navAbout:'About',navContact:'Contact',badge:'🎁 FREE TOOLS • $100 DAILY GIVEAWAY • WORLDWIDE',heroTitle:'Free Tools That Help You Save Money',heroDesc:'Use free calculators, converters and everyday tools — and enter our daily $100 giveaway.',enter:'🎁 Enter $100 Giveaway',search:'Search tools...',smart:'✨ Smart Tool Finder',smartTitle:'What do you need to calculate?',shareTitle:'🎁 Share the $100 Daily Giveaway',shareDesc:'Share the giveaway with friends and family.',giveawayTitle:'Win $100 Every Day',giveawayDesc:'Worldwide $100 daily giveaway. Enter free during the active campaign period.',today:'🎁 Enter Today’s Giveaway',prize:'Today’s Prize',live:'🎉 LIVE GIVEAWAY',shareGive:'🎁 Share the Giveaway',shareGiveDesc:'Share with friends and family so they can enter too.',location:'Choose your language',locationSub:'We’ll personalize the giveaway experience for you.',country:'Country',state:'State / Region',language:'Language',apply:'Save preferences',auto:'Auto-detect when possible',saved:'Preferences saved'},
 hi:{navTools:'टूल्स',navRewards:'🎁 इनाम',navWinners:'🏆 विजेता',navAbout:'हमारे बारे में',navContact:'संपर्क',badge:'🎁 फ्री टूल्स • हर दिन $100 गिवअवे • दुनिया भर में',heroTitle:'पैसे बचाने में मदद करने वाले फ्री टूल्स',heroDesc:'फ्री कैलकुलेटर और रोज़मर्रा के टूल्स इस्तेमाल करें — और हर दिन $100 गिवअवे में शामिल हों।',enter:'🎁 $100 गिवअवे में शामिल हों',search:'टूल खोजें...',smart:'✨ स्मार्ट टूल फाइंडर',smartTitle:'आपको क्या कैलकुलेट करना है?',shareTitle:'🎁 $100 डेली गिवअवे शेयर करें',shareDesc:'गिवअवे को दोस्तों और परिवार के साथ शेयर करें।',giveawayTitle:'हर दिन $100 जीतने का मौका',giveawayDesc:'दुनिया भर के योग्य प्रतिभागियों के लिए फ्री डेली गिवअवे।',today:'🎁 आज के गिवअवे में शामिल हों',prize:'आज का इनाम',live:'🎉 गिवअवे LIVE है',shareGive:'🎁 गिवअवे शेयर करें',shareGiveDesc:'दोस्तों और परिवार के साथ शेयर करें ताकि वे भी शामिल हो सकें।',location:'अपनी भाषा चुनें',locationSub:'हम गिवअवे अनुभव को आपके लिए पर्सनलाइज़ करेंगे।',country:'देश',state:'राज्य / क्षेत्र',language:'भाषा',apply:'सेटिंग सेव करें',auto:'जहाँ संभव हो ऑटो-डिटेक्ट करें',saved:'सेटिंग सेव हो गई'},
 es:{navTools:'Herramientas',navRewards:'🎁 Premios',navWinners:'🏆 Ganadores',navAbout:'Acerca de',navContact:'Contacto',badge:'🎁 HERRAMIENTAS GRATIS • $100 CADA DÍA • TODO EL MUNDO',heroTitle:'Herramientas gratis para ayudarte a ahorrar',heroDesc:'Usa calculadoras y herramientas gratuitas — y participa en nuestro sorteo diario de $100.',enter:'🎁 Participar por $100',search:'Buscar herramientas...',smart:'✨ Buscador inteligente',smartTitle:'¿Qué necesitas calcular?',shareTitle:'🎁 Comparte el sorteo diario de $100',shareDesc:'Comparte el sorteo con amigos y familiares.',giveawayTitle:'Gana $100 cada día',giveawayDesc:'Sorteo mundial diario de $100. Participa gratis durante la campaña.',today:'🎁 Participar hoy',prize:'Premio de hoy',live:'🎉 SORTEO ACTIVO',shareGive:'🎁 Comparte el sorteo',shareGiveDesc:'Compártelo para que tus amigos también puedan participar.',location:'Elige tu idioma',locationSub:'Personalizaremos la experiencia del sorteo.',country:'País',state:'Estado / Región',language:'Idioma',apply:'Guardar preferencias',auto:'Detectar automáticamente cuando sea posible',saved:'Preferencias guardadas'},
 pt:{navTools:'Ferramentas',navRewards:'🎁 Prêmios',navWinners:'🏆 Vencedores',navAbout:'Sobre',navContact:'Contato',badge:'🎁 FERRAMENTAS GRÁTIS • $100 TODO DIA • MUNDO TODO',heroTitle:'Ferramentas grátis para ajudar você a economizar',heroDesc:'Use calculadoras e ferramentas grátis — e participe do sorteio diário de $100.',enter:'🎁 Participar do sorteio de $100',search:'Pesquisar ferramentas...',smart:'✨ Buscador inteligente',smartTitle:'O que você precisa calcular?',shareTitle:'🎁 Compartilhe o sorteio diário de $100',shareDesc:'Compartilhe com amigos e familiares.',giveawayTitle:'Ganhe $100 todos os dias',giveawayDesc:'Sorteio mundial diário de $100. Participação gratuita durante a campanha.',today:'🎁 Participar hoje',prize:'Prêmio de hoje',live:'🎉 SORTEIO ATIVO',shareGive:'🎁 Compartilhe o sorteio',shareGiveDesc:'Compartilhe para que seus amigos também possam participar.',location:'Escolha seu idioma',locationSub:'Vamos personalizar a experiência do sorteio.',country:'País',state:'Estado / Região',language:'Idioma',apply:'Salvar preferências',auto:'Detectar automaticamente quando possível',saved:'Preferências salvas'},
 fr:{navTools:'Outils',navRewards:'🎁 Récompenses',navWinners:'🏆 Gagnants',navAbout:'À propos',navContact:'Contact',badge:'🎁 OUTILS GRATUITS • 100 $ CHAQUE JOUR • MONDE ENTIER',heroTitle:'Des outils gratuits pour vous aider à économiser',heroDesc:'Utilisez des calculateurs et outils gratuits — et participez à notre tirage quotidien de 100 $.',enter:'🎁 Participer pour 100 $',search:'Rechercher des outils...',smart:'✨ Recherche intelligente',smartTitle:'Que voulez-vous calculer ?',shareTitle:'🎁 Partagez le tirage quotidien de 100 $',shareDesc:'Partagez le tirage avec vos amis et votre famille.',giveawayTitle:'Gagnez 100 $ chaque jour',giveawayDesc:'Tirage quotidien mondial de 100 $. Participation gratuite pendant la campagne.',today:'🎁 Participer aujourd’hui',prize:'Prix du jour',live:'🎉 TIRAGE EN COURS',shareGive:'🎁 Partager le tirage',shareGiveDesc:'Partagez-le pour inviter vos proches.',location:'Choisissez votre langue',locationSub:'Nous personnalisons votre expérience.',country:'Pays',state:'État / Région',language:'Langue',apply:'Enregistrer',auto:'Détection automatique si possible',saved:'Préférences enregistrées'},
 de:{navTools:'Tools',navRewards:'🎁 Prämien',navWinners:'🏆 Gewinner',navAbout:'Über uns',navContact:'Kontakt',badge:'🎁 KOSTENLOSE TOOLS • 100 $ JEDEN TAG • WELTWEIT',heroTitle:'Kostenlose Tools, die Ihnen beim Sparen helfen',heroDesc:'Nutzen Sie kostenlose Rechner und Tools — und nehmen Sie an unserer täglichen 100-$-Verlosung teil.',enter:'🎁 An der 100-$-Verlosung teilnehmen',search:'Tools suchen...',smart:'✨ Smarte Tool-Suche',smartTitle:'Was möchten Sie berechnen?',shareTitle:'🎁 Tägliche 100-$-Verlosung teilen',shareDesc:'Teilen Sie die Verlosung mit Freunden und Familie.',giveawayTitle:'Jeden Tag 100 $ gewinnen',giveawayDesc:'Weltweite tägliche 100-$-Verlosung. Die Teilnahme ist während der Kampagne kostenlos.',today:'🎁 Heute teilnehmen',prize:'Heutiger Gewinn',live:'🎉 VERLOSUNG AKTIV',shareGive:'🎁 Verlosung teilen',shareGiveDesc:'Teilen Sie sie, damit auch andere teilnehmen können.',location:'Sprache wählen',locationSub:'Wir personalisieren die Verlosung für Sie.',country:'Land',state:'Bundesland / Region',language:'Sprache',apply:'Einstellungen speichern',auto:'Wenn möglich automatisch erkennen',saved:'Einstellungen gespeichert'},
 it:{navTools:'Strumenti',navRewards:'🎁 Premi',navWinners:'🏆 Vincitori',navAbout:'Chi siamo',navContact:'Contatti',badge:'🎁 STRUMENTI GRATIS • 100 $ OGNI GIORNO • IN TUTTO IL MONDO',heroTitle:'Strumenti gratuiti per aiutarti a risparmiare',heroDesc:'Usa calcolatori e strumenti gratuiti — e partecipa al nostro giveaway giornaliero da 100 $.',enter:'🎁 Partecipa al giveaway da 100 $',search:'Cerca strumenti...',smart:'✨ Ricerca intelligente',smartTitle:'Cosa devi calcolare?',shareTitle:'🎁 Condividi il giveaway giornaliero da 100 $',shareDesc:'Condividi il giveaway con amici e familiari.',giveawayTitle:'Vinci 100 $ ogni giorno',giveawayDesc:'Giveaway giornaliero mondiale da 100 $. Partecipazione gratuita durante la campagna.',today:'🎁 Partecipa oggi',prize:'Premio di oggi',live:'🎉 GIVEAWAY ATTIVO',shareGive:'🎁 Condividi il giveaway',shareGiveDesc:'Condividilo per invitare altre persone.',location:'Scegli la lingua',locationSub:'Personalizzeremo la tua esperienza.',country:'Paese',state:'Stato / Regione',language:'Lingua',apply:'Salva preferenze',auto:'Rileva automaticamente quando possibile',saved:'Preferenze salvate'},
 tr:{navTools:'Araçlar',navRewards:'🎁 Ödüller',navWinners:'🏆 Kazananlar',navAbout:'Hakkımızda',navContact:'İletişim',badge:'🎁 ÜCRETSİZ ARAÇLAR • HER GÜN 100 $ • DÜNYA ÇAPINDA',heroTitle:'Tasarruf etmenize yardımcı ücretsiz araçlar',heroDesc:'Ücretsiz hesap makinelerini kullanın — ve günlük 100 $ çekilişine katılın.',enter:'🎁 100 $ Çekilişine Katıl',search:'Araçlarda ara...',smart:'✨ Akıllı Araç Bulucu',smartTitle:'Neyi hesaplamak istiyorsunuz?',shareTitle:'🎁 Günlük 100 $ çekilişini paylaş',shareDesc:'Çekilişi arkadaşlarınız ve ailenizle paylaşın.',giveawayTitle:'Her gün 100 $ kazan',giveawayDesc:'Dünya çapında günlük 100 $ çekilişi. Kampanya süresince katılım ücretsizdir.',today:'🎁 Bugün katıl',prize:'Bugünün ödülü',live:'🎉 ÇEKİLİŞ AKTİF',shareGive:'🎁 Çekilişi paylaş',shareGiveDesc:'Arkadaşlarınızın da katılabilmesi için paylaşın.',location:'Dil seçin',locationSub:'Çekiliş deneyimini sizin için kişiselleştireceğiz.',country:'Ülke',state:'Eyalet / Bölge',language:'Dil',apply:'Tercihleri kaydet',auto:'Mümkünse otomatik algıla',saved:'Tercihler kaydedildi'},
 ja:{navTools:'ツール',navRewards:'🎁 リワード',navWinners:'🏆 当選者',navAbout:'概要',navContact:'お問い合わせ',badge:'🎁 無料ツール • 毎日100ドル • 世界対応',heroTitle:'節約に役立つ無料ツール',heroDesc:'無料の計算ツールを使って、毎日100ドルのキャンペーンにも参加できます。',enter:'🎁 100ドルキャンペーンに参加',search:'ツールを検索...',smart:'✨ スマートツール検索',smartTitle:'何を計算しますか？',shareTitle:'🎁 毎日100ドルキャンペーンを共有',shareDesc:'友達や家族と共有しましょう。',giveawayTitle:'毎日100ドルを獲得',giveawayDesc:'世界対応の毎日100ドルキャンペーン。期間中は無料で参加できます。',today:'🎁 今日参加する',prize:'今日の賞金',live:'🎉 キャンペーン開催中',shareGive:'🎁 キャンペーンを共有',shareGiveDesc:'友達も参加できるように共有しましょう。',location:'言語を選択',locationSub:'キャンペーン体験をパーソナライズします。',country:'国',state:'都道府県 / 地域',language:'言語',apply:'設定を保存',auto:'可能な場合は自動検出',saved:'設定を保存しました'},
 ko:{navTools:'도구',navRewards:'🎁 리워드',navWinners:'🏆 당첨자',navAbout:'소개',navContact:'문의',badge:'🎁 무료 도구 • 매일 $100 • 전 세계',heroTitle:'돈을 절약하는 데 도움이 되는 무료 도구',heroDesc:'무료 계산기와 도구를 사용하고 매일 $100 이벤트에도 참여하세요.',enter:'🎁 $100 이벤트 참여',search:'도구 검색...',smart:'✨ 스마트 도구 찾기',smartTitle:'무엇을 계산할까요?',shareTitle:'🎁 매일 $100 이벤트 공유',shareDesc:'친구와 가족에게 이벤트를 공유하세요.',giveawayTitle:'매일 $100 당첨 기회',giveawayDesc:'전 세계 대상 매일 $100 이벤트입니다. 캠페인 기간 동안 무료로 참여할 수 있습니다.',today:'🎁 오늘 참여하기',prize:'오늘의 상금',live:'🎉 이벤트 진행 중',shareGive:'🎁 이벤트 공유',shareGiveDesc:'친구도 참여할 수 있도록 공유하세요.',location:'언어 선택',locationSub:'이벤트 경험을 맞춤 설정합니다.',country:'국가',state:'주 / 지역',language:'언어',apply:'설정 저장',auto:'가능하면 자동 감지',saved:'설정이 저장되었습니다'}
};
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function detect(){
 const saved=localStorage.getItem('uftLocale'); if(saved) return JSON.parse(saved);
 const nav=(navigator.language||'en').toLowerCase(); let lang=nav.slice(0,2); if(!LANGS[lang]) lang='en';
 const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'';
 let country='United States'; if(tz.startsWith('Asia/Kolkata')||tz.startsWith('Asia/Calcutta')) country='India'; else if(tz.startsWith('Europe/')) country=lang==='de'?'Germany':lang==='fr'?'France':lang==='it'?'Italy':lang==='es'?'Spain':lang==='tr'?'Türkiye':'Europe'; else if(tz.startsWith('Asia/Tokyo')) country='Japan'; else if(tz.startsWith('Asia/Seoul')) country='South Korea'; else if(tz.startsWith('America/Sao_Paulo')) country='Brazil';
 return {lang,country,state:''};
}
let pref=detect();
function t(k){return (T[pref.lang]||T.en)[k]||T.en[k]||k;}
function applyText(){
 document.documentElement.lang=pref.lang;
 const q=s=>document.querySelector(s);
 const set=(s,k)=>{const e=q(s);if(e)e.textContent=t(k)};
 const attr=(s,a,k)=>{const e=q(s);if(e)e.setAttribute(a,t(k))};
 if(location.pathname.endsWith('index.html')||location.pathname==='/'||location.pathname===''){
  const nav=q('.nav-links'); if(nav){const as=nav.querySelectorAll('a'); if(as[0])as[0].textContent=t('navTools');if(as[1])as[1].textContent=t('navRewards');if(as[2])as[2].textContent=t('navWinners');if(as[3])as[3].textContent=t('navAbout');if(as[4])as[4].textContent=t('navContact');}
  set('.badge','badge');set('.hero h1','heroTitle');set('.hero p','heroDesc');
  const heroBtn=q('.hero a[href="rewards.html"]');if(heroBtn)heroBtn.textContent=t('enter');attr('#toolSearch','placeholder','search');set('.smart-badge','smart');set('.smart-assistant h2','smartTitle');set('.share-card h2','shareTitle');set('.share-card p','shareDesc');
 }
 if(location.pathname.endsWith('rewards.html')){
  set('.hero h1','giveawayTitle');set('.hero p','giveawayDesc');set('.hero .btn','today');set('#enter h2','prize');set('#enter .status','live');set('.share-card h2','shareGive');set('.share-card p','shareGiveDesc');
 }
 buildLocaleUI();
}
function buildLocaleUI(){
 if(document.getElementById('uftLocaleRoot')) return;
 const root=document.createElement('div');root.id='uftLocaleRoot';
 root.innerHTML='<button class="uft-locale-btn" type="button" aria-expanded="false">🌐 '+esc((LANGS[pref.lang]||LANGS.en).name)+' <span>⌄</span></button><div class="uft-locale-panel"><div class="uft-locale-head"><strong>'+esc(t('location'))+'</strong><span>'+esc(t('locationSub'))+'</span></div><div class="uft-locale-body"><label>'+esc(t('country'))+'</label><select class="uft-locale-select" id="uftCountry"></select><label>'+esc(t('state'))+'</label><select class="uft-locale-select" id="uftState"><option value="">—</option></select><label>'+esc(t('language'))+'</label><select class="uft-locale-select" id="uftLang"></select><button class="uft-locale-apply" type="button">'+esc(t('apply'))+'</button><p class="uft-locale-note">'+esc(t('auto'))+'</p></div></div>';
 document.body.appendChild(root);
 const btn=root.querySelector('.uft-locale-btn'),panel=root.querySelector('.uft-locale-panel'),country=root.querySelector('#uftCountry'),state=root.querySelector('#uftState'),lang=root.querySelector('#uftLang');
 Object.entries(LANGS).forEach(([code,v])=>{lang.add(new Option(v.flag+' '+v.name,code))}); lang.value=pref.lang;
 const countries=[...new Set(Object.values(LANGS).map(v=>v.country).concat(['India','United States','Canada','United Kingdom','Australia','Mexico','Argentina','South Africa']))].sort(); countries.forEach(c=>country.add(new Option(c,c))); country.value=pref.country;
 function states(){state.innerHTML='<option value="">—</option>';if(country.value==='India')INDIA_STATES.forEach(s=>state.add(new Option(s,s)));state.value=pref.state||'';state.disabled=country.value!=='India';}
 states(); country.onchange=states;
 btn.onclick=()=>{panel.classList.toggle('open');btn.setAttribute('aria-expanded',panel.classList.contains('open'))};
 root.querySelector('.uft-locale-apply').onclick=()=>{pref={lang:lang.value,country:country.value,state:state.value};localStorage.setItem('uftLocale',JSON.stringify(pref));panel.classList.remove('open');applyText();toast(t('saved'));};
 document.addEventListener('click',e=>{if(!root.contains(e.target))panel.classList.remove('open')},{passive:true});
}
function toast(msg){let x=document.querySelector('.uft-locale-toast');if(!x){x=document.createElement('div');x.className='uft-locale-toast';document.body.appendChild(x)}x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
async function geoSuggest(){
 if(localStorage.getItem('uftLocale')) return;
 try{const r=await fetch('https://ipapi.co/json/',{headers:{Accept:'application/json'}});if(!r.ok)return;const d=await r.json();let lang=(d.languages||'').split(',')[0].slice(0,2).toLowerCase();if(!LANGS[lang]){const map={IN:'hi',US:'en',GB:'en',CA:'en',AU:'en',ES:'es',BR:'pt',PT:'pt',FR:'fr',DE:'de',IT:'it',TR:'tr',JP:'ja',KR:'ko'};lang=map[d.country_code]||pref.lang;}pref={lang,country:d.country_name||pref.country,state:d.region||''};applyText();}catch(e){}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{applyText();geoSuggest()});else{applyText();geoSuggest()}
})();
