-- USA Free Tools — Mystery Box 100,000-click milestone system
-- Free-entry promotion: 3 pre-assigned random milestones between 1 and 100,000.
-- Do NOT put Amazon Pay codes in HTML/JS. Add them only in Supabase Table Editor.

create table if not exists public.mystery_reward_codes (
  id bigint generated by default as identity primary key,
  reward_amount numeric(10,2) not null check (reward_amount in (1,2,5)),
  reward_code text not null unique,
  claimed_at timestamptz,
  claimed_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.mystery_box_campaign (
  id bigint primary key default 1 check (id = 1),
  total_clicks bigint not null default 0,
  max_clicks bigint not null default 100000,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.mystery_box_campaign (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.mystery_box_milestones (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.mystery_box_campaign(id),
  reward_code_id bigint not null references public.mystery_reward_codes(id),
  milestone bigint not null check (milestone between 1 and 100000),
  claimed_at timestamptz,
  claimed_by text,
  unique (campaign_id, reward_code_id),
  unique (campaign_id, milestone)
);

create table if not exists public.mystery_box_clicks (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.mystery_box_campaign(id),
  email text not null,
  click_date date not null default (timezone('utc', now())::date),
  click_number bigint not null,
  created_at timestamptz not null default now(),
  unique (campaign_id, email, click_date)
);

alter table public.mystery_reward_codes enable row level security;
alter table public.mystery_box_campaign enable row level security;
alter table public.mystery_box_milestones enable row level security;
alter table public.mystery_box_clicks enable row level security;

revoke all on public.mystery_reward_codes from anon, authenticated;
revoke all on public.mystery_box_milestones from anon, authenticated;
revoke all on public.mystery_box_clicks from anon, authenticated;
revoke all on public.mystery_box_campaign from anon, authenticated;

-- Run this ONCE after adding exactly three codes: one $5, one $2 and one $1.
create or replace function public.initialize_mystery_milestones()
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if exists (select 1 from public.mystery_box_milestones where campaign_id=1) then
    raise exception 'Mystery milestones are already initialized';
  end if;

  if (select count(*) from public.mystery_reward_codes
      where claimed_at is null and reward_amount in (1,2,5)) < 3 then
    raise exception 'Add at least three unused codes: one $5, one $2 and one $1';
  end if;

  with chosen_codes as (
    select id, reward_amount,
           row_number() over (order by case reward_amount when 5 then 1 when 2 then 2 when 1 then 3 else 9 end) rn
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount in (1,2,5)
      and reward_amount in (1,2,5)
    order by case reward_amount when 5 then 1 when 2 then 2 when 1 then 3 else 9 end, id
    limit 3
  ),
  chosen_slots as (
    select milestone,
           row_number() over (order by random()) rn
    from generate_series(1,100000) as milestone
    order by random()
    limit 3
  )
  insert into public.mystery_box_milestones(campaign_id,reward_code_id,milestone)
  select 1, c.id, s.milestone
  from chosen_codes c
  join chosen_slots s using (rn);
end;
$$;

-- Public status: exposes only progress, never codes or winning milestones.
create or replace function public.mystery_box_status()
returns table(total_clicks bigint, max_clicks bigint, active boolean, winners_remaining integer)
language sql
security definer
set search_path=public
as $$
  select
    c.total_clicks,
    c.max_clicks,
    c.active,
    (select count(*)::integer from public.mystery_box_milestones m
      where m.campaign_id=c.id and m.claimed_at is null)
  from public.mystery_box_campaign c
  where c.id=1;
$$;

-- One eligible Mystery Box click per email per UTC day.
-- A click is NOT an ad click and users must never be asked to click ads.
create or replace function public.claim_mystery_box(p_email text)
returns table(won boolean, reward_amount numeric, reward_code text, click_number bigint, total_clicks bigint, max_clicks bigint)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_email text := lower(trim(p_email));
  v_campaign record;
  v_click_no bigint;
  v_milestone record;
begin
  if v_email is null or length(v_email) < 5 or position('@' in v_email) < 2 then
    raise exception 'Valid email required';
  end if;

  select * into v_campaign
  from public.mystery_box_campaign
  where id=1
  for update;

  if not v_campaign.active or v_campaign.total_clicks >= v_campaign.max_clicks then
    raise exception 'Mystery Box campaign has ended';
  end if;

  if exists (
    select 1 from public.mystery_box_clicks
    where campaign_id=1 and email=v_email
      and click_date=timezone('utc',now())::date
  ) then
    raise exception 'You already used your eligible Mystery Box click today';
  end if;

  v_click_no := v_campaign.total_clicks + 1;

  insert into public.mystery_box_clicks(campaign_id,email,click_date,click_number)
  values(1,v_email,timezone('utc',now())::date,v_click_no);

  update public.mystery_box_campaign
  set total_clicks=v_click_no,
      active=case when v_click_no >= max_clicks then false else active end
  where id=1;

  select * into v_milestone
  from public.mystery_box_milestones
  where campaign_id=1 and milestone=v_click_no and claimed_at is null
  for update;

  if found then
    update public.mystery_box_milestones
    set claimed_at=now(), claimed_by=v_email
    where id=v_milestone.id;

    update public.mystery_reward_codes
    set claimed_at=now(), claimed_by=v_email
    where id=v_milestone.reward_code_id;

    return query
    select true, rc.reward_amount, rc.reward_code,
           v_click_no, v_click_no, v_campaign.max_clicks
    from public.mystery_reward_codes rc
    where rc.id=v_milestone.reward_code_id;
    return;
  end if;

  return query
  select false, null::numeric, null::text,
         v_click_no, v_click_no, v_campaign.max_clicks;
end;
$$;

revoke all on function public.initialize_mystery_milestones() from public;
revoke all on function public.mystery_box_status() from public;
revoke all on function public.claim_mystery_box(text) from public;

grant execute on function public.mystery_box_status() to anon, authenticated;
grant execute on function public.claim_mystery_box(text) to anon, authenticated;

-- initialize_mystery_milestones() should be run manually by the owner AFTER
-- inserting exactly one $5, one $2 and one $1 code.
