-- USA Free Tools — Daily Mystery Box
-- 100,000 global eligible openings per day.
-- Each email gets up to 3 eligible openings per UTC day.
-- Winners: #500, #50,000, and one random milestone from #90,001–#100,000.
-- Amazon Pay codes remain server-side in Supabase.

create table if not exists public.mystery_box_daily_campaign (
  campaign_date date primary key,
  total_clicks bigint not null default 0,
  max_clicks bigint not null default 100000,
  active boolean not null default true,
  late_winner_click bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.mystery_reward_codes (
  id bigint generated by default as identity primary key,
  reward_amount numeric(10,2) not null check (reward_amount in (1,2,5)),
  reward_code text not null unique,
  claimed_at timestamptz,
  claimed_by text,
  claimed_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.mystery_box_daily_clicks (
  id bigint generated by default as identity primary key,
  campaign_date date not null references public.mystery_box_daily_campaign(campaign_date),
  email text not null,
  attempt_no smallint not null check (attempt_no between 1 and 3),
  click_number bigint not null,
  created_at timestamptz not null default now(),
  unique(campaign_date,email,attempt_no),
  unique(campaign_date,click_number)
);

alter table public.mystery_box_daily_campaign enable row level security;
alter table public.mystery_reward_codes enable row level security;
alter table public.mystery_box_daily_clicks enable row level security;

revoke all on public.mystery_box_daily_campaign from anon, authenticated;
revoke all on public.mystery_reward_codes from anon, authenticated;
revoke all on public.mystery_box_daily_clicks from anon, authenticated;

create or replace function public.mystery_box_status()
returns table(
  campaign_date date,
  total_clicks bigint,
  max_clicks bigint,
  active boolean,
  late_winner_click bigint
)
language plpgsql
security definer
set search_path=public
as $$
declare
  d date := timezone('utc',now())::date;
begin
  insert into public.mystery_box_daily_campaign(campaign_date,late_winner_click)
  values(d, floor(random()*10000)::bigint + 90001)
  on conflict (campaign_date) do nothing;

  return query
  select c.campaign_date,c.total_clicks,c.max_clicks,c.active,c.late_winner_click
  from public.mystery_box_daily_campaign c
  where c.campaign_date=d;
end;
$$;

create or replace function public.claim_mystery_box(p_email text)
returns table(
  won boolean,
  reward_amount numeric,
  reward_code text,
  click_number bigint,
  total_clicks bigint,
  max_clicks bigint,
  attempts_left integer
)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_email text := lower(trim(p_email));
  d date := timezone('utc',now())::date;
  c record;
  v_attempt smallint;
  v_click bigint;
  v_reward_id bigint;
  v_amount numeric;
  v_code text;
begin
  if v_email is null or length(v_email)<5 or position('@' in v_email)<2 then
    raise exception 'Valid email required';
  end if;

  insert into public.mystery_box_daily_campaign(campaign_date,late_winner_click)
  values(d,floor(random()*10000)::bigint+90001)
  on conflict(campaign_date) do nothing;

  select * into c
  from public.mystery_box_daily_campaign
  where campaign_date=d
  for update;

  if not c.active or c.total_clicks>=c.max_clicks then
    raise exception 'Today''s Mystery Box campaign is complete';
  end if;

  select coalesce(max(attempt_no),0)+1 into v_attempt
  from public.mystery_box_daily_clicks
  where campaign_date=d and email=v_email;

  if v_attempt>3 then
    raise exception 'You have used all 3 Mystery Box chances today';
  end if;

  v_click:=c.total_clicks+1;

  insert into public.mystery_box_daily_clicks(campaign_date,email,attempt_no,click_number)
  values(d,v_email,v_attempt,v_click);

  update public.mystery_box_daily_campaign
  set total_clicks=v_click,
      active=(v_click<c.max_clicks)
  where campaign_date=d;

  if v_click=500 then
    select id,reward_amount,reward_code into v_reward_id,v_amount,v_code
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount=1
    order by created_at,id limit 1
    for update;
  elsif v_click=50000 then
    select id,reward_amount,reward_code into v_reward_id,v_amount,v_code
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount=2
    order by created_at,id limit 1
    for update;
  elsif v_click=c.late_winner_click then
    select id,reward_amount,reward_code into v_reward_id,v_amount,v_code
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount=5
    order by created_at,id limit 1
    for update;
  end if;

  if v_reward_id is not null then
    update public.mystery_reward_codes
    set claimed_at=now(),claimed_by=v_email,claimed_date=d
    where id=v_reward_id;

    return query
    select true,v_amount,v_code,v_click,v_click,c.max_clicks,3-v_attempt;
    return;
  end if;

  return query
  select false,null::numeric,null::text,v_click,v_click,c.max_clicks,3-v_attempt;
end;
$$;

revoke all on function public.mystery_box_status() from public;
revoke all on function public.claim_mystery_box(text) from public;
grant execute on function public.mystery_box_status() to anon,authenticated;
grant execute on function public.claim_mystery_box(text) to anon,authenticated;
