-- USA Free Tools - Secure Mystery Box setup
create table if not exists public.mystery_reward_codes (
 id bigint generated by default as identity primary key,
 reward_amount numeric(10,2) not null check (reward_amount in (1,2,5)),
 reward_code text not null unique,
 claimed_at timestamptz,
 claimed_by text,
 created_at timestamptz not null default now()
);
create table if not exists public.mystery_reward_claims (
 id bigint generated by default as identity primary key,
 email text not null,
 reward_code_id bigint not null references public.mystery_reward_codes(id),
 reward_amount numeric(10,2) not null,
 claimed_at timestamptz not null default now(),
 claim_date date not null default (timezone('utc', now())::date),
 unique(email, claim_date)
);
alter table public.mystery_reward_codes enable row level security;
alter table public.mystery_reward_claims enable row level security;
revoke all on public.mystery_reward_codes from anon, authenticated;
revoke all on public.mystery_reward_claims from anon, authenticated;
create or replace function public.claim_mystery_box(p_email text)
returns table(reward_amount numeric, reward_code text)
language plpgsql security definer set search_path=public
as $$
declare v_email text:=lower(trim(p_email)); v_id bigint; v_amount numeric(10,2); v_code text; v_roll numeric; v_date date:=timezone('utc',now())::date;
begin
 if v_email is null or length(v_email)<5 or position('@' in v_email)<2 then raise exception 'Valid email required'; end if;
 if exists(select 1 from public.mystery_reward_claims where email=v_email and claim_date=v_date) then raise exception 'Already claimed today'; end if;
 v_roll:=random(); v_amount:=case when v_roll<0.70 then 1 when v_roll<0.95 then 2 else 5 end;
 select id,reward_amount,reward_code into v_id,v_amount,v_code from public.mystery_reward_codes where claimed_at is null and reward_amount=v_amount order by random() limit 1 for update skip locked;
 if v_id is null then select id,reward_amount,reward_code into v_id,v_amount,v_code from public.mystery_reward_codes where claimed_at is null order by random() limit 1 for update skip locked; end if;
 if v_id is null then raise exception 'Mystery Box is temporarily sold out. Please try again later.'; end if;
 update public.mystery_reward_codes set claimed_at=now(),claimed_by=v_email where id=v_id;
 insert into public.mystery_reward_claims(email,reward_code_id,reward_amount,claim_date) values(v_email,v_id,v_amount,v_date);
 return query select v_amount,v_code;
end; $$;
revoke all on function public.claim_mystery_box(text) from public;
grant execute on function public.claim_mystery_box(text) to anon, authenticated;
-- Add real codes only in Supabase Table Editor; never put them in HTML/JS.
