-- USA Free Tools — Mystery Box 100K NON-RESET campaign
-- ONE campaign total: 100,000 eligible Mystery Box openings.
-- Each email can make up to 3 eligible openings per UTC day.
-- Counter NEVER resets daily.
-- Winners: #500 = $1, #50,000 = $2, one random milestone #90,001–#100,000 = $5.
-- Add exactly one unused code for each reward before initializing the late milestone.

create table if not exists public.mystery_box_campaign (
  id bigint primary key default 1 check (id=1),
  total_clicks bigint not null default 0,
  max_clicks bigint not null default 100000,
  active boolean not null default true,
  late_winner_click bigint,
  created_at timestamptz not null default now()
);

insert into public.mystery_box_campaign(id)
values(1)
on conflict(id) do nothing;

create table if not exists public.mystery_reward_codes (
  id bigint generated by default as identity primary key,
  reward_amount numeric(10,2) not null check (reward_amount in (1,2,5)),
  reward_code text not null unique,
  claimed_at timestamptz,
  claimed_by text,
  claimed_at_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.mystery_box_attempts (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.mystery_box_campaign(id),
  email text not null,
  attempt_date date not null default (timezone('utc',now())::date),
  attempt_no smallint not null check(attempt_no between 1 and 3),
  click_number bigint not null,
  created_at timestamptz not null default now(),
  unique(campaign_id,email,attempt_date,attempt_no),
  unique(campaign_id,click_number)
);

alter table public.mystery_box_campaign enable row level security;
alter table public.mystery_reward_codes enable row level security;
alter table public.mystery_box_attempts enable row level security;

revoke all on public.mystery_box_campaign from anon, authenticated;
revoke all on public.mystery_reward_codes from anon, authenticated;
revoke all on public.mystery_box_attempts from anon, authenticated;

-- Run ONCE after the 3 codes are added.
-- The random late winning position is hidden from public users.
create or replace function public.initialize_mystery_box_campaign()
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_late bigint;
begin
  select late_winner_click into v_late
  from public.mystery_box_campaign
  where id=1
  for update;

  if v_late is not null then
    return v_late;
  end if;

  if (select count(*) from public.mystery_reward_codes
      where claimed_at is null and reward_amount in (1,2,5)) < 3 then
    raise exception 'Add one unused $1, one unused $2 and one unused $5 code first';
  end if;

  v_late := floor(random()*10000)::bigint + 90001;

  update public.mystery_box_campaign
  set late_winner_click=v_late
  where id=1;

  return v_late;
end;
$$;

create or replace function public.mystery_box_status()
returns table(
  total_clicks bigint,
  max_clicks bigint,
  active boolean
)
language sql
security definer
set search_path=public
as $$
  select total_clicks,max_clicks,active
  from public.mystery_box_campaign
  where id=1;
$$;

create or replace function public.claim_mystery_box(p_email text)
returns table(
  won boolean,
  reward_amount numeric,
  reward_code text,
  click_number bigint,
  total_clicks bigint,
  max_clicks bigint,
  attempts_left integer
)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_email text := lower(trim(p_email));
  v_today date := timezone('utc',now())::date;
  v_campaign record;
  v_attempt smallint;
  v_click bigint;
  v_reward_id bigint;
  v_amount numeric;
  v_code text;
begin
  if v_email is null or length(v_email)<5 or position('@' in v_email)<2 then
    raise exception 'Valid email required';
  end if;

  select * into v_campaign
  from public.mystery_box_campaign
  where id=1
  for update;

  if not v_campaign.active or v_campaign.total_clicks>=v_campaign.max_clicks then
    raise exception 'The 100,000 Mystery Box campaign is complete';
  end if;

  select coalesce(max(attempt_no),0)+1
  into v_attempt
  from public.mystery_box_attempts
  where campaign_id=1 and email=v_email and attempt_date=v_today;

  if v_attempt>3 then
    raise exception 'You have used all 3 Mystery Box chances today';
  end if;

  v_click:=v_campaign.total_clicks+1;

  insert into public.mystery_box_attempts(
    campaign_id,email,attempt_date,attempt_no,click_number
  ) values(
    1,v_email,v_today,v_attempt,v_click
  );

  update public.mystery_box_campaign
  set total_clicks=v_click,
      active=(v_click<max_clicks)
  where id=1;

  -- #500 => $1
  if v_click=500 then
    select id,reward_amount,reward_code
    into v_reward_id,v_amount,v_code
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount=1
    order by id limit 1
    for update;

  -- #50,000 => $2
  elsif v_click=50000 then
    select id,reward_amount,reward_code
    into v_reward_id,v_amount,v_code
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount=2
    order by id limit 1
    for update;

  -- Random #90,001–#100,000 => $5
  elsif v_campaign.late_winner_click is not null
        and v_click=v_campaign.late_winner_click then
    select id,reward_amount,reward_code
    into v_reward_id,v_amount,v_code
    from public.mystery_reward_codes
    where claimed_at is null and reward_amount=5
    order by id limit 1
    for update;
  end if;

  if v_reward_id is not null then
    update public.mystery_reward_codes
    set claimed_at=now(),
        claimed_by=v_email,
        claimed_at_date=v_today
    where id=v_reward_id;

    return query
    select true,v_amount,v_code,v_click,v_click,v_campaign.max_clicks,3-v_attempt;
    return;
  end if;

  return query
  select false,null::numeric,null::text,v_click,v_click,
         v_campaign.max_clicks,3-v_attempt;
end;
$$;

revoke all on function public.initialize_mystery_box_campaign() from public;
revoke all on function public.mystery_box_status() from public;
revoke all on function public.claim_mystery_box(text) from public;

grant execute on function public.mystery_box_status() to anon,authenticated;
grant execute on function public.claim_mystery_box(text) to anon,authenticated;
